### ISSUE TITLE
Unable to install composer based Acquia Lightning distro

### ISSUE THREAD

**Issue by ivangrynenko** [beetboxvm/beetbox#454]
I cannot install an Acquia Lightning distribution (https://github.com/acquia/lightning-project) in beetboxvm, either using `drush si`, `phing` or web-based installer. The error about the missing "list" plugin appears across any installation method.

## Expected behaviour

`drush si` installs the site with no errors

## Actual behaviour

```
vagrant@project-folder:/var/beetbox$ vendor/drush/drush/drush -r docroot site-install lightning \
>     --db-url=mysql://beetbox:beetbox@localhost:3306/beetbox \
>     --db-su=root --db-su-pw="" \
>     --account-name=admin --account-pass=beetbox \
>     --account-mail=myemail@domain.com --locale=en --site-name="Some site name" \
>     --site-mail=myemail@domain.com --yes

 // You are about to create a sites/default/settings.php file and create a sites/sites.php file and DROP all tables in  
 // your 'beetbox' database. Do you want to continue?: yes.                                                             

 [notice] Starting Drupal installation. This takes a while.
 **[error]  The "list" plugin does not exist.** 
```

Using bundled drush 8.x:

```
vagrant@project-folder:/var/beetbox$ drush -r docroot site-install lightning     --db-url=mysql://beetbox:beetbox@localhost:3306/beetbox     --db-su=root --db-su-pw=""     --account-name=admin --account-pass=beetbox     --account-mail=myemail@domain.com --locale=en --site-name="Some site name"     --site-mail=myemail@domain.com --yes
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Drush\Sql\SqlBase::__construct(), 1 passed and exactly 2 expected in /var/beetbox/vendor/drush/drush/src/Sql/SqlBase.php:29
Stack trace:
#0 [internal function]: Drush\Sql\SqlBase->__construct(Array)
#1 /usr/local/share/drush/includes/drush.inc(117): ReflectionClass->newInstanceArgs(Array)
#2 /usr/local/share/drush/commands/sql/sql.drush.inc(523): drush_get_class('Drush\\Sql\\Sql', Array, Array)
#3 /usr/local/share/drush/commands/sql/sql.drush.inc(530): drush_sql_get_class(Array)
#4 /usr/local/share/drush/commands/core/site_install.drush.inc(123): drush_sql_get_class()
#5 /usr/local/share/drush/includes/command.inc(422): drush_core_pre_site_install('lightning')
#6 /usr/local/share/drush/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#7 /usr/local/share/drush/includes/command.inc(199): drush_command('lightning')
#8 /usr/local/share/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#9 /usr/local/share/drush/includes/preflight.inc in /var/beetbox/vendor/drush/drush/src/Sql/SqlBase.php on line 29

Fatal error: Uncaught ArgumentCountError: Too few arguments to function Drush\Sql\SqlBase::__construct(), 1 passed and exactly 2 expected in /var/beetbox/vendor/drush/drush/src/Sql/SqlBase.php on line 29

ArgumentCountError: Too few arguments to function Drush\Sql\SqlBase::__construct(), 1 passed and exactly 2 expected in /var/beetbox/vendor/drush/drush/src/Sql/SqlBase.php on line 29

Call Stack:
    0.0001     352320   1. {main}() /usr/local/share/drush/drush.php:0
    0.0008     497976   2. drush_main() /usr/local/share/drush/drush.php:12
    0.1446    8556592   3. Drush\Boot\BaseBoot->bootstrap_and_dispatch() /usr/local/share/drush/includes/preflight.inc:66
    0.1784    8501952   4. drush_dispatch() /usr/local/share/drush/lib/Drush/Boot/BaseBoot.php:67
    0.2385    9815544   5. drush_command() /usr/local/share/drush/includes/command.inc:199
    0.2386    9815960   6. _drush_invoke_hooks() /usr/local/share/drush/includes/command.inc:231
    0.2499   10027336   7. drush_core_pre_site_install() /usr/local/share/drush/includes/command.inc:422
    0.2499   10027336   8. drush_sql_get_class() /usr/local/share/drush/commands/core/site_install.drush.inc:123
    0.2500   10027912   9. drush_sql_get_class() /usr/local/share/drush/commands/sql/sql.drush.inc:530
    0.2501   10029104  10. drush_get_class() /usr/local/share/drush/commands/sql/sql.drush.inc:523
    0.2525   10131680  11. ReflectionClass->newInstanceArgs() /usr/local/share/drush/includes/drush.inc:117
    0.2525   10131808  12. Drush\Sql\SqlBase->__construct() /usr/local/share/drush/includes/drush.inc:117

Drush command terminated abnormally due to an unrecoverable error.                                                                                                                             [error]
Error: Uncaught ArgumentCountError: Too few arguments to function Drush\Sql\SqlBase::__construct(), 1 passed and exactly 2 expected in /var/beetbox/vendor/drush/drush/src/Sql/SqlBase.php:29
Stack trace:
#0 [internal function]: Drush\Sql\SqlBase->__construct(Array)
#1 /usr/local/share/drush/includes/drush.inc(117): ReflectionClass->newInstanceArgs(Array)
#2 /usr/local/share/drush/commands/sql/sql.drush.inc(523): drush_get_class('Drush\\Sql\\Sql', Array, Array)
#3 /usr/local/share/drush/commands/sql/sql.drush.inc(530): drush_sql_get_class(Array)
#4 /usr/local/share/drush/commands/core/site_install.drush.inc(123): drush_sql_get_class()
#5 /usr/local/share/drush/includes/command.inc(422): drush_core_pre_site_install('lightning')
#6 /usr/local/share/drush/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#7 /usr/local/share/drush/includes/command.inc(199): drush_command('lightning')
#8 /usr/local/share/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#9 /usr/local/share/drush/includes/preflight.inc in /var/beetbox/vendor/drush/drush/src/Sql/SqlBase.php, line 29
```
## Steps to reproduce

```
composer create-project acquia/lightning-project project_folder
cd project_folder
composer require --dev beet/box
vagrant up
vagrant ssh
cd ../
vendor/drush/drush/drush -r docroot site-install lightning \
    --db-url=mysql://beetbox:beetbox@localhost:3306/beetbox \
    --db-su=root --db-su-pw="" \
    --account-name=admin --account-pass=beetbox \
    --account-mail=myemail@domain.com --locale=en --site-name="Some site name" \
    --site-mail=myemail@domain.com --yes
```
Note! Lightning using Drush 9.x beta, but using Beetbox's bundled drush 8.x does not help.

Alternatively, using web-based install allows to select the language and throws the same error, described here https://github.com/acquia/lightning/issues/477

To eliminate composer install, tried in a fresh install pulling the docroot (including all dependencies) from Github repo, with the same outcome

```
mkdir project_folder_2
cd project_folder_2
wget https://github.com/acquia/lightning/releases/download/2.2.0/lightning-8.x-2.20.tar.gz
tar -xzpf lightning-8.x-2.20.tar.gz
mv lightning-8.x-2.20 docroot
composer require --dev beet/box
vagrant up
```

And the error (same as the above, with the "list" plugin not found) is described here: https://github.com/acquia/lightning/issues/477

## Proposed changes

None

Would you be able to clarify steps to install Acquia Lightning in beetbox?

**Comment by ivangrynenko** [comment]
Same as #455

**Comment by thom8** [comment]
Ah yeah #455 still isn't resolved.
